---
- hosts: 127.0.0.1
  user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  connection: local
  tasks:
    - name: Install Node
      apt:
        name: apache2
        state: present
